# This file is machine-generated - editing it directly is not advised

julia_version = "1.9.3"
manifest_format = "2.0"
project_hash = "0c5e7fa0737a7b52053cf742901a39f52ef20713"

[[deps.ThreadTools]]
git-tree-sha1 = "e335e40d393ccc1e1aa8087632989e856db988e0"
uuid = "dbf13d8f-d36e-4350-8970-f3a99faba1a8"
version = "0.2.0"
