[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
MakieTeX = "6d554a22-29e7-47bd-aee5-0c5f06619414"
OhMyREPL = "5fb14364-9ced-5910-84b2-373655c76a03"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
ThreadTools = "dbf13d8f-d36e-4350-8970-f3a99faba1a8"
