[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
MakieTeX = "6d554a22-29e7-47bd-aee5-0c5f06619414"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
ThreadTools = "dbf13d8f-d36e-4350-8970-f3a99faba1a8"
